// GENERATED CODE - DO NOT MODIFY BY HAND

// ignore_for_file: non_constant_identifier_names

part of 'tweet_withheld.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_TweetWithheld _$$_TweetWithheldFromJson(Map json) => $checkedCreate(
      r'_$_TweetWithheld',
      json,
      ($checkedConvert) {
        final val = _$_TweetWithheld(
          dueToCopyright: $checkedConvert('copyright', (v) => v as bool),
          countries: $checkedConvert(
              'country_codes',
              (v) => (v as List<dynamic>)
                  .map((e) => $enumDecode(_$WithheldCountryEnumMap, e))
                  .toList()),
        );
        return val;
      },
      fieldKeyMap: const {
        'dueToCopyright': 'copyright',
        'countries': 'country_codes'
      },
    );

Map<String, dynamic> _$$_TweetWithheldToJson(_$_TweetWithheld instance) =>
    <String, dynamic>{
      'copyright': instance.dueToCopyright,
      'country_codes':
          instance.countries.map((e) => _$WithheldCountryEnumMap[e]!).toList(),
    };

const _$WithheldCountryEnumMap = {
  WithheldCountry.afghanistan: 'AF',
  WithheldCountry.alandIslands: 'AX',
  WithheldCountry.albania: 'AL',
  WithheldCountry.algeria: 'DZ',
  WithheldCountry.americanSamoa: 'AS',
  WithheldCountry.andorra: 'AD',
  WithheldCountry.angola: 'AO',
  WithheldCountry.anguilla: 'AI',
  WithheldCountry.antarctica: 'AQ',
  WithheldCountry.antiguaAndBarbuda: 'AG',
  WithheldCountry.argentina: 'AR',
  WithheldCountry.armenia: 'AM',
  WithheldCountry.aruba: 'AW',
  WithheldCountry.australia: 'AU',
  WithheldCountry.austria: 'AT',
  WithheldCountry.azerbaijan: 'AZ',
  WithheldCountry.bahamas: 'BS',
  WithheldCountry.bahrain: 'BH',
  WithheldCountry.bangladesh: 'BD',
  WithheldCountry.barbados: 'BB',
  WithheldCountry.belarus: 'BY',
  WithheldCountry.belgium: 'BE',
  WithheldCountry.belize: 'BZ',
  WithheldCountry.benin: 'BJ',
  WithheldCountry.bermuda: 'BM',
  WithheldCountry.bhutan: 'BT',
  WithheldCountry.bolivia: 'BO',
  WithheldCountry.bonaire: 'BQ',
  WithheldCountry.bosniaAndHerzegovina: 'BA',
  WithheldCountry.botswana: 'BW',
  WithheldCountry.bouvetIsland: 'BV',
  WithheldCountry.brazil: 'BR',
  WithheldCountry.britishIndianOceanTerritory: 'IO',
  WithheldCountry.bruneiDarussalam: 'BN',
  WithheldCountry.bulgaria: 'BG',
  WithheldCountry.burkinaFaso: 'BF',
  WithheldCountry.burundi: 'BI',
  WithheldCountry.cambodia: 'KH',
  WithheldCountry.cameroon: 'CM',
  WithheldCountry.canada: 'CA',
  WithheldCountry.capeVerde: 'CV',
  WithheldCountry.caymanIslands: 'KY',
  WithheldCountry.centralAfricanRepublic: 'CF',
  WithheldCountry.chad: 'TD',
  WithheldCountry.chile: 'CL',
  WithheldCountry.china: 'CN',
  WithheldCountry.christmasIsland: 'CX',
  WithheldCountry.cocosIslands: 'CC',
  WithheldCountry.colombia: 'CO',
  WithheldCountry.comoros: 'KM',
  WithheldCountry.congo: 'CD',
  WithheldCountry.cookIslands: 'CK',
  WithheldCountry.costaRica: 'CR',
  WithheldCountry.ivoryCoast: 'CI',
  WithheldCountry.croatia: 'HR',
  WithheldCountry.cuba: 'CU',
  WithheldCountry.curacao: 'CW',
  WithheldCountry.cyprus: 'CY',
  WithheldCountry.czechRepublic: 'CZ',
  WithheldCountry.denmark: 'DK',
  WithheldCountry.djibouti: 'DJ',
  WithheldCountry.dominica: 'DM',
  WithheldCountry.dominicanRepublic: 'DO',
  WithheldCountry.ecuador: 'EC',
  WithheldCountry.egypt: 'EG',
  WithheldCountry.elSalvador: 'SV',
  WithheldCountry.equatorialGuinea: 'GQ',
  WithheldCountry.eritrea: 'ER',
  WithheldCountry.estonia: 'EE',
  WithheldCountry.ethiopia: 'ET',
  WithheldCountry.falklandIslands: 'FK',
  WithheldCountry.faroeIslands: 'FO',
  WithheldCountry.fiji: 'FJ',
  WithheldCountry.finland: 'FI',
  WithheldCountry.france: 'FR',
  WithheldCountry.frenchGuiana: 'GF',
  WithheldCountry.frenchPolynesia: 'PF',
  WithheldCountry.frenchSouthernTerritories: 'TF',
  WithheldCountry.gabon: 'GA',
  WithheldCountry.gambia: 'GM',
  WithheldCountry.georgia: 'GE',
  WithheldCountry.germany: 'DE',
  WithheldCountry.ghana: 'GH',
  WithheldCountry.gibraltar: 'GI',
  WithheldCountry.greece: 'GR',
  WithheldCountry.greenland: 'GL',
  WithheldCountry.grenada: 'GD',
  WithheldCountry.guadeloupe: 'GP',
  WithheldCountry.guam: 'GU',
  WithheldCountry.guatemala: 'GT',
  WithheldCountry.guernsey: 'GG',
  WithheldCountry.guinea: 'GN',
  WithheldCountry.guineaBissau: 'GW',
  WithheldCountry.guyana: 'GY',
  WithheldCountry.haiti: 'HT',
  WithheldCountry.heardIslandAndMcDonaldIslands: 'HM',
  WithheldCountry.holySee: 'VA',
  WithheldCountry.honduras: 'HN',
  WithheldCountry.hongKong: 'HK',
  WithheldCountry.hungary: 'HU',
  WithheldCountry.iceland: 'IS',
  WithheldCountry.india: 'IN',
  WithheldCountry.indonesia: 'ID',
  WithheldCountry.iran: 'IR',
  WithheldCountry.iraq: 'IQ',
  WithheldCountry.ireland: 'IE',
  WithheldCountry.isleOfMan: 'IM',
  WithheldCountry.israel: 'IL',
  WithheldCountry.italy: 'IT',
  WithheldCountry.jamaica: 'JM',
  WithheldCountry.japan: 'JP',
  WithheldCountry.jersey: 'JE',
  WithheldCountry.jordan: 'JO',
  WithheldCountry.kazakhstan: 'KZ',
  WithheldCountry.kenya: 'KE',
  WithheldCountry.kiribati: 'KI',
  WithheldCountry.northKorea: 'KP',
  WithheldCountry.korea: 'KR',
  WithheldCountry.kuwait: 'KW',
  WithheldCountry.kyrgyzstan: 'KG',
  WithheldCountry.laoPeoplesDemocraticRepublic: 'LA',
  WithheldCountry.latvia: 'LV',
  WithheldCountry.lebanon: 'LB',
  WithheldCountry.lesotho: 'LS',
  WithheldCountry.liberia: 'LR',
  WithheldCountry.libya: 'LY',
  WithheldCountry.liechtenstein: 'LI',
  WithheldCountry.lithuania: 'LT',
  WithheldCountry.luxembourg: 'LU',
  WithheldCountry.macao: 'MO',
  WithheldCountry.macedonia: 'MK',
  WithheldCountry.madagascar: 'MG',
  WithheldCountry.malawi: 'MW',
  WithheldCountry.malaysia: 'MY',
  WithheldCountry.maldives: 'MV',
  WithheldCountry.mali: 'ML',
  WithheldCountry.malta: 'MT',
  WithheldCountry.marshallIslands: 'MH',
  WithheldCountry.martinique: 'MQ',
  WithheldCountry.mauritania: 'MR',
  WithheldCountry.mauritius: 'MU',
  WithheldCountry.mayotte: 'YT',
  WithheldCountry.mexico: 'MX',
  WithheldCountry.micronesia: 'FM',
  WithheldCountry.moldova: 'MD',
  WithheldCountry.monaco: 'MC',
  WithheldCountry.mongolia: 'MN',
  WithheldCountry.montenegro: 'ME',
  WithheldCountry.montserrat: 'MS',
  WithheldCountry.morocco: 'MA',
  WithheldCountry.mozambique: 'MZ',
  WithheldCountry.myanmar: 'MM',
  WithheldCountry.namibia: 'NA',
  WithheldCountry.nauru: 'NR',
  WithheldCountry.nepal: 'NP',
  WithheldCountry.netherlands: 'NL',
  WithheldCountry.newCaledonia: 'NC',
  WithheldCountry.newZealand: 'NZ',
  WithheldCountry.nicaragua: 'NI',
  WithheldCountry.niger: 'NE',
  WithheldCountry.nigeria: 'NG',
  WithheldCountry.niue: 'NU',
  WithheldCountry.norfolkIsland: 'NF',
  WithheldCountry.northernMarianaIslands: 'MP',
  WithheldCountry.norway: 'NO',
  WithheldCountry.oman: 'OM',
  WithheldCountry.pakistan: 'PK',
  WithheldCountry.palau: 'PW',
  WithheldCountry.palestine: 'PS',
  WithheldCountry.panama: 'PA',
  WithheldCountry.papuaNewGuinea: 'PG',
  WithheldCountry.paraguay: 'PY',
  WithheldCountry.peru: 'PE',
  WithheldCountry.philippines: 'PH',
  WithheldCountry.pitcairn: 'PN',
  WithheldCountry.poland: 'PL',
  WithheldCountry.portugal: 'PT',
  WithheldCountry.puertoRico: 'PR',
  WithheldCountry.qatar: 'QA',
  WithheldCountry.reunion: 'RE',
  WithheldCountry.romania: 'RO',
  WithheldCountry.russianFederation: 'RU',
  WithheldCountry.rwanda: 'RW',
  WithheldCountry.saintBarthelemy: 'BL',
  WithheldCountry.saintHelena: 'SH',
  WithheldCountry.saintKittsAndNevis: 'KN',
  WithheldCountry.saintLucia: 'LC',
  WithheldCountry.saintMartin: 'MF',
  WithheldCountry.saintPierreAndMiquelon: 'PM',
  WithheldCountry.saintVincentAndTheGrenadines: 'VC',
  WithheldCountry.samoa: 'WS',
  WithheldCountry.sanMarino: 'SM',
  WithheldCountry.saoTomeAndPrincipe: 'ST',
  WithheldCountry.saudiArabia: 'SA',
  WithheldCountry.senegal: 'SN',
  WithheldCountry.serbia: 'RS',
  WithheldCountry.seychelles: 'SC',
  WithheldCountry.sierraLeone: 'SL',
  WithheldCountry.singapore: 'SG',
  WithheldCountry.sintMaarten: 'SX',
  WithheldCountry.slovakia: 'SK',
  WithheldCountry.slovenia: 'SI',
  WithheldCountry.solomonIslands: 'SB',
  WithheldCountry.somalia: 'SO',
  WithheldCountry.southAfrica: 'ZA',
  WithheldCountry.southGeorgiaAndTheSouthSandwichIslands: 'GS',
  WithheldCountry.southSudan: 'SS',
  WithheldCountry.spain: 'ES',
  WithheldCountry.sriLanka: 'LK',
  WithheldCountry.sudan: 'SD',
  WithheldCountry.suriname: 'SR',
  WithheldCountry.svalbardAndJanMayen: 'SJ',
  WithheldCountry.swaziland: 'SZ',
  WithheldCountry.sweden: 'SE',
  WithheldCountry.switzerland: 'CH',
  WithheldCountry.syrianArabRepublic: 'SY',
  WithheldCountry.taiwan: 'TW',
  WithheldCountry.tajikistan: 'TJ',
  WithheldCountry.tanzania: 'TZ',
  WithheldCountry.thailand: 'TH',
  WithheldCountry.timorLeste: 'TL',
  WithheldCountry.togo: 'TG',
  WithheldCountry.tokelau: 'TK',
  WithheldCountry.tonga: 'TO',
  WithheldCountry.trinidadAndTobago: 'TT',
  WithheldCountry.tunisia: 'TN',
  WithheldCountry.turkey: 'TR',
  WithheldCountry.turkmenistan: 'TM',
  WithheldCountry.turksAndCaicosIslands: 'TC',
  WithheldCountry.tuvalu: 'TV',
  WithheldCountry.uganda: 'UG',
  WithheldCountry.ukraine: 'UA',
  WithheldCountry.unitedArabEmirates: 'AE',
  WithheldCountry.unitedKingdom: 'GB',
  WithheldCountry.unitedStates: 'US',
  WithheldCountry.unitedStatesMinorOutlyingIslands: 'UM',
  WithheldCountry.uruguay: 'UY',
  WithheldCountry.uzbekistan: 'UZ',
  WithheldCountry.vanuatu: 'VU',
  WithheldCountry.venezuela: 'VE',
  WithheldCountry.vietnam: 'VN',
  WithheldCountry.virginIslandsBritish: 'VG',
  WithheldCountry.virginIslandsUS: 'VI',
  WithheldCountry.wallisAndFutuna: 'WF',
  WithheldCountry.westernSahara: 'EH',
  WithheldCountry.yemen: 'YE',
  WithheldCountry.zambia: 'ZM',
  WithheldCountry.zimbabwe: 'ZW',
  WithheldCountry.allCountries: 'XX',
  WithheldCountry.dmcaRequest: 'XY',
};
