client:
- lib/src/client/*.dart

service/Tweets:
- lib/src/service/tweets/*.dart

service/Users:
- lib/src/service/users/*.dart

service/Spaces:
- lib/src/service/spaces/*.dart

service/Lists:
- lib/src/service/lists/*.dart

service/Compliance:
- lib/src/service/compliance/*.dart

service/Media:
- lib/src/service/media/*.dart

test:
- test/**/*.dart
