// Copyright 2022 Kato Shinya. All rights reserved.
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided the conditions.

// 📦 Package imports:
import 'package:test/test.dart';

// 🌎 Project imports:
import 'package:twitter_api_v2/src/core/country.dart';

void main() {
  test('.name', () {
    expect(Country.afghanistan.name, 'afghanistan');
    expect(Country.alandIslands.name, 'alandIslands');
    expect(Country.albania.name, 'albania');
    expect(Country.algeria.name, 'algeria');
    expect(Country.americanSamoa.name, 'americanSamoa');
    expect(Country.andorra.name, 'andorra');
    expect(Country.angola.name, 'angola');
    expect(Country.anguilla.name, 'anguilla');
    expect(Country.antarctica.name, 'antarctica');
    expect(Country.antiguaAndBarbuda.name, 'antiguaAndBarbuda');
    expect(Country.argentina.name, 'argentina');
    expect(Country.armenia.name, 'armenia');
    expect(Country.aruba.name, 'aruba');
    expect(Country.australia.name, 'australia');
    expect(Country.austria.name, 'austria');
    expect(Country.azerbaijan.name, 'azerbaijan');
    expect(Country.bahamas.name, 'bahamas');
    expect(Country.bahrain.name, 'bahrain');
    expect(Country.bangladesh.name, 'bangladesh');
    expect(Country.barbados.name, 'barbados');
    expect(Country.belarus.name, 'belarus');
    expect(Country.belgium.name, 'belgium');
    expect(Country.belize.name, 'belize');
    expect(Country.benin.name, 'benin');
    expect(Country.bermuda.name, 'bermuda');
    expect(Country.bhutan.name, 'bhutan');
    expect(Country.bolivia.name, 'bolivia');
    expect(Country.bonaire.name, 'bonaire');
    expect(Country.bosniaAndHerzegovina.name, 'bosniaAndHerzegovina');
    expect(Country.botswana.name, 'botswana');
    expect(Country.bouvetIsland.name, 'bouvetIsland');
    expect(Country.brazil.name, 'brazil');
    expect(Country.britishIndianOceanTerritory.name,
        'britishIndianOceanTerritory');
    expect(Country.bruneiDarussalam.name, 'bruneiDarussalam');
    expect(Country.bulgaria.name, 'bulgaria');
    expect(Country.burkinaFaso.name, 'burkinaFaso');
    expect(Country.burundi.name, 'burundi');
    expect(Country.cambodia.name, 'cambodia');
    expect(Country.cameroon.name, 'cameroon');
    expect(Country.canada.name, 'canada');
    expect(Country.capeVerde.name, 'capeVerde');
    expect(Country.caymanIslands.name, 'caymanIslands');
    expect(Country.centralAfricanRepublic.name, 'centralAfricanRepublic');
    expect(Country.chad.name, 'chad');
    expect(Country.chile.name, 'chile');
    expect(Country.china.name, 'china');
    expect(Country.christmasIsland.name, 'christmasIsland');
    expect(Country.cocosIslands.name, 'cocosIslands');
    expect(Country.colombia.name, 'colombia');
    expect(Country.comoros.name, 'comoros');
    expect(Country.congo.name, 'congo');
    expect(Country.cookIslands.name, 'cookIslands');
    expect(Country.costaRica.name, 'costaRica');
    expect(Country.ivoryCoast.name, 'ivoryCoast');
    expect(Country.croatia.name, 'croatia');
    expect(Country.cuba.name, 'cuba');
    expect(Country.curacao.name, 'curacao');
    expect(Country.cyprus.name, 'cyprus');
    expect(Country.czechRepublic.name, 'czechRepublic');
    expect(Country.denmark.name, 'denmark');
    expect(Country.djibouti.name, 'djibouti');
    expect(Country.dominica.name, 'dominica');
    expect(Country.dominicanRepublic.name, 'dominicanRepublic');
    expect(Country.ecuador.name, 'ecuador');
    expect(Country.egypt.name, 'egypt');
    expect(Country.elSalvador.name, 'elSalvador');
    expect(Country.equatorialGuinea.name, 'equatorialGuinea');
    expect(Country.eritrea.name, 'eritrea');
    expect(Country.estonia.name, 'estonia');
    expect(Country.ethiopia.name, 'ethiopia');
    expect(Country.falklandIslands.name, 'falklandIslands');
    expect(Country.faroeIslands.name, 'faroeIslands');
    expect(Country.fiji.name, 'fiji');
    expect(Country.finland.name, 'finland');
    expect(Country.france.name, 'france');
    expect(Country.frenchGuiana.name, 'frenchGuiana');
    expect(Country.frenchPolynesia.name, 'frenchPolynesia');
    expect(Country.frenchSouthernTerritories.name, 'frenchSouthernTerritories');
    expect(Country.gabon.name, 'gabon');
    expect(Country.gambia.name, 'gambia');
    expect(Country.georgia.name, 'georgia');
    expect(Country.germany.name, 'germany');
    expect(Country.ghana.name, 'ghana');
    expect(Country.gibraltar.name, 'gibraltar');
    expect(Country.greece.name, 'greece');
    expect(Country.greenland.name, 'greenland');
    expect(Country.grenada.name, 'grenada');
    expect(Country.guadeloupe.name, 'guadeloupe');
    expect(Country.guam.name, 'guam');
    expect(Country.guatemala.name, 'guatemala');
    expect(Country.guernsey.name, 'guernsey');
    expect(Country.guinea.name, 'guinea');
    expect(Country.guineaBissau.name, 'guineaBissau');
    expect(Country.guyana.name, 'guyana');
    expect(Country.haiti.name, 'haiti');
    expect(Country.heardIslandAndMcDonaldIslands.name,
        'heardIslandAndMcDonaldIslands');
    expect(Country.holySee.name, 'holySee');
    expect(Country.honduras.name, 'honduras');
    expect(Country.hongKong.name, 'hongKong');
    expect(Country.hungary.name, 'hungary');
    expect(Country.iceland.name, 'iceland');
    expect(Country.india.name, 'india');
    expect(Country.indonesia.name, 'indonesia');
    expect(Country.iran.name, 'iran');
    expect(Country.iraq.name, 'iraq');
    expect(Country.ireland.name, 'ireland');
    expect(Country.isleOfMan.name, 'isleOfMan');
    expect(Country.israel.name, 'israel');
    expect(Country.italy.name, 'italy');
    expect(Country.jamaica.name, 'jamaica');
    expect(Country.japan.name, 'japan');
    expect(Country.jersey.name, 'jersey');
    expect(Country.jordan.name, 'jordan');
    expect(Country.kazakhstan.name, 'kazakhstan');
    expect(Country.kenya.name, 'kenya');
    expect(Country.kiribati.name, 'kiribati');
    expect(Country.korea.name, 'korea');
    expect(Country.kuwait.name, 'kuwait');
    expect(Country.kyrgyzstan.name, 'kyrgyzstan');
    expect(Country.laoPeoplesDemocraticRepublic.name,
        'laoPeoplesDemocraticRepublic');
    expect(Country.latvia.name, 'latvia');
    expect(Country.lebanon.name, 'lebanon');
    expect(Country.lesotho.name, 'lesotho');
    expect(Country.liberia.name, 'liberia');
    expect(Country.libya.name, 'libya');
    expect(Country.liechtenstein.name, 'liechtenstein');
    expect(Country.lithuania.name, 'lithuania');
    expect(Country.luxembourg.name, 'luxembourg');
    expect(Country.macao.name, 'macao');
    expect(Country.macedonia.name, 'macedonia');
    expect(Country.madagascar.name, 'madagascar');
    expect(Country.malawi.name, 'malawi');
    expect(Country.malaysia.name, 'malaysia');
    expect(Country.maldives.name, 'maldives');
    expect(Country.mali.name, 'mali');
    expect(Country.malta.name, 'malta');
    expect(Country.marshallIslands.name, 'marshallIslands');
    expect(Country.martinique.name, 'martinique');
    expect(Country.mauritania.name, 'mauritania');
    expect(Country.mauritius.name, 'mauritius');
    expect(Country.mayotte.name, 'mayotte');
    expect(Country.mexico.name, 'mexico');
    expect(Country.micronesia.name, 'micronesia');
    expect(Country.moldova.name, 'moldova');
    expect(Country.monaco.name, 'monaco');
    expect(Country.mongolia.name, 'mongolia');
    expect(Country.montenegro.name, 'montenegro');
    expect(Country.montserrat.name, 'montserrat');
    expect(Country.morocco.name, 'morocco');
    expect(Country.mozambique.name, 'mozambique');
    expect(Country.myanmar.name, 'myanmar');
    expect(Country.namibia.name, 'namibia');
    expect(Country.nauru.name, 'nauru');
    expect(Country.nepal.name, 'nepal');
    expect(Country.netherlands.name, 'netherlands');
    expect(Country.newCaledonia.name, 'newCaledonia');
    expect(Country.newZealand.name, 'newZealand');
    expect(Country.nicaragua.name, 'nicaragua');
    expect(Country.niger.name, 'niger');
    expect(Country.nigeria.name, 'nigeria');
    expect(Country.niue.name, 'niue');
    expect(Country.norfolkIsland.name, 'norfolkIsland');
    expect(Country.northernMarianaIslands.name, 'northernMarianaIslands');
    expect(Country.norway.name, 'norway');
    expect(Country.oman.name, 'oman');
    expect(Country.pakistan.name, 'pakistan');
    expect(Country.palau.name, 'palau');
    expect(Country.palestine.name, 'palestine');
    expect(Country.panama.name, 'panama');
    expect(Country.papuaNewGuinea.name, 'papuaNewGuinea');
    expect(Country.paraguay.name, 'paraguay');
    expect(Country.peru.name, 'peru');
    expect(Country.philippines.name, 'philippines');
    expect(Country.pitcairn.name, 'pitcairn');
    expect(Country.poland.name, 'poland');
    expect(Country.portugal.name, 'portugal');
    expect(Country.puertoRico.name, 'puertoRico');
    expect(Country.qatar.name, 'qatar');
    expect(Country.reunion.name, 'reunion');
    expect(Country.romania.name, 'romania');
    expect(Country.russianFederation.name, 'russianFederation');
    expect(Country.rwanda.name, 'rwanda');
    expect(Country.saintBarthelemy.name, 'saintBarthelemy');
    expect(Country.saintHelena.name, 'saintHelena');
    expect(Country.saintKittsAndNevis.name, 'saintKittsAndNevis');
    expect(Country.saintLucia.name, 'saintLucia');
    expect(Country.saintMartin.name, 'saintMartin');
    expect(Country.saintPierreAndMiquelon.name, 'saintPierreAndMiquelon');
    expect(Country.saintVincentAndTheGrenadines.name,
        'saintVincentAndTheGrenadines');
    expect(Country.samoa.name, 'samoa');
    expect(Country.sanMarino.name, 'sanMarino');
    expect(Country.saoTomeAndPrincipe.name, 'saoTomeAndPrincipe');
    expect(Country.saudiArabia.name, 'saudiArabia');
    expect(Country.senegal.name, 'senegal');
    expect(Country.serbia.name, 'serbia');
    expect(Country.seychelles.name, 'seychelles');
    expect(Country.sierraLeone.name, 'sierraLeone');
    expect(Country.singapore.name, 'singapore');
    expect(Country.sintMaarten.name, 'sintMaarten');
    expect(Country.slovakia.name, 'slovakia');
    expect(Country.slovenia.name, 'slovenia');
    expect(Country.solomonIslands.name, 'solomonIslands');
    expect(Country.somalia.name, 'somalia');
    expect(Country.southAfrica.name, 'southAfrica');
    expect(Country.southGeorgiaAndTheSouthSandwichIslands.name,
        'southGeorgiaAndTheSouthSandwichIslands');
    expect(Country.southSudan.name, 'southSudan');
    expect(Country.spain.name, 'spain');
    expect(Country.sriLanka.name, 'sriLanka');
    expect(Country.sudan.name, 'sudan');
    expect(Country.suriname.name, 'suriname');
    expect(Country.svalbardAndJanMayen.name, 'svalbardAndJanMayen');
    expect(Country.swaziland.name, 'swaziland');
    expect(Country.sweden.name, 'sweden');
    expect(Country.switzerland.name, 'switzerland');
    expect(Country.syrianArabRepublic.name, 'syrianArabRepublic');
    expect(Country.taiwan.name, 'taiwan');
    expect(Country.tajikistan.name, 'tajikistan');
    expect(Country.tanzania.name, 'tanzania');
    expect(Country.thailand.name, 'thailand');
    expect(Country.timorLeste.name, 'timorLeste');
    expect(Country.togo.name, 'togo');
    expect(Country.tokelau.name, 'tokelau');
    expect(Country.tonga.name, 'tonga');
    expect(Country.trinidadAndTobago.name, 'trinidadAndTobago');
    expect(Country.tunisia.name, 'tunisia');
    expect(Country.turkey.name, 'turkey');
    expect(Country.turkmenistan.name, 'turkmenistan');
    expect(Country.turksAndCaicosIslands.name, 'turksAndCaicosIslands');
    expect(Country.tuvalu.name, 'tuvalu');
    expect(Country.uganda.name, 'uganda');
    expect(Country.ukraine.name, 'ukraine');
    expect(Country.unitedArabEmirates.name, 'unitedArabEmirates');
    expect(Country.unitedKingdom.name, 'unitedKingdom');
    expect(Country.unitedStates.name, 'unitedStates');
    expect(Country.unitedStatesMinorOutlyingIslands.name,
        'unitedStatesMinorOutlyingIslands');
    expect(Country.uruguay.name, 'uruguay');
    expect(Country.uzbekistan.name, 'uzbekistan');
    expect(Country.vanuatu.name, 'vanuatu');
    expect(Country.venezuela.name, 'venezuela');
    expect(Country.vietnam.name, 'vietnam');
    expect(Country.virginIslandsBritish.name, 'virginIslandsBritish');
    expect(Country.virginIslandsUS.name, 'virginIslandsUS');
    expect(Country.wallisAndFutuna.name, 'wallisAndFutuna');
    expect(Country.westernSahara.name, 'westernSahara');
    expect(Country.yemen.name, 'yemen');
    expect(Country.zambia.name, 'zambia');
    expect(Country.zimbabwe.name, 'zimbabwe');
    expect(Country.allCountries.name, 'allCountries');
    expect(Country.dmcaRequest.name, 'dmcaRequest');
  });

  test('.code', () {
    expect(Country.afghanistan.code, 'AF');
    expect(Country.alandIslands.code, 'AX');
    expect(Country.albania.code, 'AL');
    expect(Country.algeria.code, 'DZ');
    expect(Country.americanSamoa.code, 'AS');
    expect(Country.andorra.code, 'AD');
    expect(Country.angola.code, 'AO');
    expect(Country.anguilla.code, 'AI');
    expect(Country.antarctica.code, 'AQ');
    expect(Country.antiguaAndBarbuda.code, 'AG');
    expect(Country.argentina.code, 'AR');
    expect(Country.armenia.code, 'AM');
    expect(Country.aruba.code, 'AW');
    expect(Country.australia.code, 'AU');
    expect(Country.austria.code, 'AT');
    expect(Country.azerbaijan.code, 'AZ');
    expect(Country.bahamas.code, 'BS');
    expect(Country.bahrain.code, 'BH');
    expect(Country.bangladesh.code, 'BD');
    expect(Country.barbados.code, 'BB');
    expect(Country.belarus.code, 'BY');
    expect(Country.belgium.code, 'BE');
    expect(Country.belize.code, 'BZ');
    expect(Country.benin.code, 'BJ');
    expect(Country.bermuda.code, 'BM');
    expect(Country.bhutan.code, 'BT');
    expect(Country.bolivia.code, 'BO');
    expect(Country.bonaire.code, 'BQ');
    expect(Country.bosniaAndHerzegovina.code, 'BA');
    expect(Country.botswana.code, 'BW');
    expect(Country.bouvetIsland.code, 'BV');
    expect(Country.brazil.code, 'BR');
    expect(Country.britishIndianOceanTerritory.code, 'IO');
    expect(Country.bruneiDarussalam.code, 'BN');
    expect(Country.bulgaria.code, 'BG');
    expect(Country.burkinaFaso.code, 'BF');
    expect(Country.burundi.code, 'BI');
    expect(Country.cambodia.code, 'KH');
    expect(Country.cameroon.code, 'CM');
    expect(Country.canada.code, 'CA');
    expect(Country.capeVerde.code, 'CV');
    expect(Country.caymanIslands.code, 'KY');
    expect(Country.centralAfricanRepublic.code, 'CF');
    expect(Country.chad.code, 'TD');
    expect(Country.chile.code, 'CL');
    expect(Country.china.code, 'CN');
    expect(Country.christmasIsland.code, 'CX');
    expect(Country.cocosIslands.code, 'CC');
    expect(Country.colombia.code, 'CO');
    expect(Country.comoros.code, 'KM');
    expect(Country.congo.code, 'CD');
    expect(Country.cookIslands.code, 'CK');
    expect(Country.costaRica.code, 'CR');
    expect(Country.ivoryCoast.code, 'CI');
    expect(Country.croatia.code, 'HR');
    expect(Country.cuba.code, 'CU');
    expect(Country.curacao.code, 'CW');
    expect(Country.cyprus.code, 'CY');
    expect(Country.czechRepublic.code, 'CZ');
    expect(Country.denmark.code, 'DK');
    expect(Country.djibouti.code, 'DJ');
    expect(Country.dominica.code, 'DM');
    expect(Country.dominicanRepublic.code, 'DO');
    expect(Country.ecuador.code, 'EC');
    expect(Country.egypt.code, 'EG');
    expect(Country.elSalvador.code, 'SV');
    expect(Country.equatorialGuinea.code, 'GQ');
    expect(Country.eritrea.code, 'ER');
    expect(Country.estonia.code, 'EE');
    expect(Country.ethiopia.code, 'ET');
    expect(Country.falklandIslands.code, 'FK');
    expect(Country.faroeIslands.code, 'FO');
    expect(Country.fiji.code, 'FJ');
    expect(Country.finland.code, 'FI');
    expect(Country.france.code, 'FR');
    expect(Country.frenchGuiana.code, 'GF');
    expect(Country.frenchPolynesia.code, 'PF');
    expect(Country.frenchSouthernTerritories.code, 'TF');
    expect(Country.gabon.code, 'GA');
    expect(Country.gambia.code, 'GM');
    expect(Country.georgia.code, 'GE');
    expect(Country.germany.code, 'DE');
    expect(Country.ghana.code, 'GH');
    expect(Country.gibraltar.code, 'GI');
    expect(Country.greece.code, 'GR');
    expect(Country.greenland.code, 'GL');
    expect(Country.grenada.code, 'GD');
    expect(Country.guadeloupe.code, 'GP');
    expect(Country.guam.code, 'GU');
    expect(Country.guatemala.code, 'GT');
    expect(Country.guernsey.code, 'GG');
    expect(Country.guinea.code, 'GN');
    expect(Country.guineaBissau.code, 'GW');
    expect(Country.guyana.code, 'GY');
    expect(Country.haiti.code, 'HT');
    expect(Country.heardIslandAndMcDonaldIslands.code, 'HM');
    expect(Country.holySee.code, 'VA');
    expect(Country.honduras.code, 'HN');
    expect(Country.hongKong.code, 'HK');
    expect(Country.hungary.code, 'HU');
    expect(Country.iceland.code, 'IS');
    expect(Country.india.code, 'IN');
    expect(Country.indonesia.code, 'ID');
    expect(Country.iran.code, 'IR');
    expect(Country.iraq.code, 'IQ');
    expect(Country.ireland.code, 'IE');
    expect(Country.isleOfMan.code, 'IM');
    expect(Country.israel.code, 'IL');
    expect(Country.italy.code, 'IT');
    expect(Country.jamaica.code, 'JM');
    expect(Country.japan.code, 'JP');
    expect(Country.jersey.code, 'JE');
    expect(Country.jordan.code, 'JO');
    expect(Country.kazakhstan.code, 'KZ');
    expect(Country.kenya.code, 'KE');
    expect(Country.kiribati.code, 'KI');
    expect(Country.korea.code, 'KR');
    expect(Country.kuwait.code, 'KW');
    expect(Country.kyrgyzstan.code, 'KG');
    expect(Country.laoPeoplesDemocraticRepublic.code, 'LA');
    expect(Country.latvia.code, 'LV');
    expect(Country.lebanon.code, 'LB');
    expect(Country.lesotho.code, 'LS');
    expect(Country.liberia.code, 'LR');
    expect(Country.libya.code, 'LY');
    expect(Country.liechtenstein.code, 'LI');
    expect(Country.lithuania.code, 'LT');
    expect(Country.luxembourg.code, 'LU');
    expect(Country.macao.code, 'MO');
    expect(Country.macedonia.code, 'MK');
    expect(Country.madagascar.code, 'MG');
    expect(Country.malawi.code, 'MW');
    expect(Country.malaysia.code, 'MY');
    expect(Country.maldives.code, 'MV');
    expect(Country.mali.code, 'ML');
    expect(Country.malta.code, 'MT');
    expect(Country.marshallIslands.code, 'MH');
    expect(Country.martinique.code, 'MQ');
    expect(Country.mauritania.code, 'MR');
    expect(Country.mauritius.code, 'MU');
    expect(Country.mayotte.code, 'YT');
    expect(Country.mexico.code, 'MX');
    expect(Country.micronesia.code, 'FM');
    expect(Country.moldova.code, 'MD');
    expect(Country.monaco.code, 'MC');
    expect(Country.mongolia.code, 'MN');
    expect(Country.montenegro.code, 'ME');
    expect(Country.montserrat.code, 'MS');
    expect(Country.morocco.code, 'MA');
    expect(Country.mozambique.code, 'MZ');
    expect(Country.myanmar.code, 'MM');
    expect(Country.namibia.code, 'NA');
    expect(Country.nauru.code, 'NR');
    expect(Country.nepal.code, 'NP');
    expect(Country.netherlands.code, 'NL');
    expect(Country.newCaledonia.code, 'NC');
    expect(Country.newZealand.code, 'NZ');
    expect(Country.nicaragua.code, 'NI');
    expect(Country.niger.code, 'NE');
    expect(Country.nigeria.code, 'NG');
    expect(Country.niue.code, 'NU');
    expect(Country.norfolkIsland.code, 'NF');
    expect(Country.northernMarianaIslands.code, 'MP');
    expect(Country.norway.code, 'NO');
    expect(Country.oman.code, 'OM');
    expect(Country.pakistan.code, 'PK');
    expect(Country.palau.code, 'PW');
    expect(Country.palestine.code, 'PS');
    expect(Country.panama.code, 'PA');
    expect(Country.papuaNewGuinea.code, 'PG');
    expect(Country.paraguay.code, 'PY');
    expect(Country.peru.code, 'PE');
    expect(Country.philippines.code, 'PH');
    expect(Country.pitcairn.code, 'PN');
    expect(Country.poland.code, 'PL');
    expect(Country.portugal.code, 'PT');
    expect(Country.puertoRico.code, 'PR');
    expect(Country.qatar.code, 'QA');
    expect(Country.reunion.code, 'RE');
    expect(Country.romania.code, 'RO');
    expect(Country.russianFederation.code, 'RU');
    expect(Country.rwanda.code, 'RW');
    expect(Country.saintBarthelemy.code, 'BL');
    expect(Country.saintHelena.code, 'SH');
    expect(Country.saintKittsAndNevis.code, 'KN');
    expect(Country.saintLucia.code, 'LC');
    expect(Country.saintMartin.code, 'MF');
    expect(Country.saintPierreAndMiquelon.code, 'PM');
    expect(Country.saintVincentAndTheGrenadines.code, 'VC');
    expect(Country.samoa.code, 'WS');
    expect(Country.sanMarino.code, 'SM');
    expect(Country.saoTomeAndPrincipe.code, 'ST');
    expect(Country.saudiArabia.code, 'SA');
    expect(Country.senegal.code, 'SN');
    expect(Country.serbia.code, 'RS');
    expect(Country.seychelles.code, 'SC');
    expect(Country.sierraLeone.code, 'SL');
    expect(Country.singapore.code, 'SG');
    expect(Country.sintMaarten.code, 'SX');
    expect(Country.slovakia.code, 'SK');
    expect(Country.slovenia.code, 'SI');
    expect(Country.solomonIslands.code, 'SB');
    expect(Country.somalia.code, 'SO');
    expect(Country.southAfrica.code, 'ZA');
    expect(Country.southGeorgiaAndTheSouthSandwichIslands.code, 'GS');
    expect(Country.southSudan.code, 'SS');
    expect(Country.spain.code, 'ES');
    expect(Country.sriLanka.code, 'LK');
    expect(Country.sudan.code, 'SD');
    expect(Country.suriname.code, 'SR');
    expect(Country.svalbardAndJanMayen.code, 'SJ');
    expect(Country.swaziland.code, 'SZ');
    expect(Country.sweden.code, 'SE');
    expect(Country.switzerland.code, 'CH');
    expect(Country.syrianArabRepublic.code, 'SY');
    expect(Country.taiwan.code, 'TW');
    expect(Country.tajikistan.code, 'TJ');
    expect(Country.tanzania.code, 'TZ');
    expect(Country.thailand.code, 'TH');
    expect(Country.timorLeste.code, 'TL');
    expect(Country.togo.code, 'TG');
    expect(Country.tokelau.code, 'TK');
    expect(Country.tonga.code, 'TO');
    expect(Country.trinidadAndTobago.code, 'TT');
    expect(Country.tunisia.code, 'TN');
    expect(Country.turkey.code, 'TR');
    expect(Country.turkmenistan.code, 'TM');
    expect(Country.turksAndCaicosIslands.code, 'TC');
    expect(Country.tuvalu.code, 'TV');
    expect(Country.uganda.code, 'UG');
    expect(Country.ukraine.code, 'UA');
    expect(Country.unitedArabEmirates.code, 'AE');
    expect(Country.unitedKingdom.code, 'GB');
    expect(Country.unitedStates.code, 'US');
    expect(Country.unitedStatesMinorOutlyingIslands.code, 'UM');
    expect(Country.uruguay.code, 'UY');
    expect(Country.uzbekistan.code, 'UZ');
    expect(Country.vanuatu.code, 'VU');
    expect(Country.venezuela.code, 'VE');
    expect(Country.vietnam.code, 'VN');
    expect(Country.virginIslandsBritish.code, 'VG');
    expect(Country.virginIslandsUS.code, 'VI');
    expect(Country.wallisAndFutuna.code, 'WF');
    expect(Country.westernSahara.code, 'EH');
    expect(Country.yemen.code, 'YE');
    expect(Country.zambia.code, 'ZM');
    expect(Country.zimbabwe.code, 'ZW');
    expect(Country.allCountries.code, 'XX');
    expect(Country.dmcaRequest.code, 'XY');
  });

  group('.valueOf', () {
    test('with lower case', () {
      final actual = Country.valueOf('jp');

      expect(actual, Country.japan);
    });

    test('with upper case', () {
      final actual = Country.valueOf('JP');

      expect(actual, Country.japan);
    });

    test('with unsupported code', () {
      expect(
        () => Country.valueOf('test'),
        throwsA(
          allOf(
            isA<UnsupportedError>(),
            predicate(
              (dynamic e) => e.message == 'The code [test] is not supported.',
            ),
          ),
        ),
      );
    });
  });

  test('.standardizedValues', () {
    final actual = Country.standardizedValues;

    expect(actual.length != Country.values.length, isTrue);
    expect(actual.length == Country.values.length - 2, isTrue);
    expect(actual.contains(Country.allCountries), isFalse);
    expect(actual.contains(Country.dmcaRequest), isFalse);
  });
}
