// Mocks generated by Mockito 5.3.2 from annotations
// in twitter_api_v2/test/mocks/mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

// 🎯 Dart imports:
import 'dart:async' as _i4;

// 📦 Package imports:
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// 🌎 Project imports:
import 'package:twitter_api_v2/src/core/client/client_context.dart' as _i3;
import 'package:twitter_api_v2/src/core/client/stream_request.dart' as _i6;
import 'package:twitter_api_v2/src/core/client/user_context.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_1 extends _i1.SmartFake
    implements _i2.StreamedResponse {
  _FakeStreamedResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ClientContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientContext extends _i1.Mock implements _i3.ClientContext {
  MockClientContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response> get(
    _i5.UserContext? userContext,
    Uri? uri,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [
            userContext,
            uri,
          ],
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #get,
            [
              userContext,
              uri,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Response>);
  @override
  _i4.Future<_i2.Response> post(
    _i5.UserContext? userContext,
    Uri? uri, {
    Map<String, String>? headers = const {},
    dynamic body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [
            userContext,
            uri,
          ],
          {
            #headers: headers,
            #body: body,
          },
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #post,
            [
              userContext,
              uri,
            ],
            {
              #headers: headers,
              #body: body,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response>);
  @override
  _i4.Future<_i2.Response> postMultipart(
    _i5.UserContext? userContext,
    Uri? uri, {
    List<_i2.MultipartFile>? files = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postMultipart,
          [
            userContext,
            uri,
          ],
          {#files: files},
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #postMultipart,
            [
              userContext,
              uri,
            ],
            {#files: files},
          ),
        )),
      ) as _i4.Future<_i2.Response>);
  @override
  _i4.Future<_i2.Response> delete(
    _i5.UserContext? userContext,
    Uri? uri,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [
            userContext,
            uri,
          ],
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #delete,
            [
              userContext,
              uri,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Response>);
  @override
  _i4.Future<_i2.Response> put(
    _i5.UserContext? userContext,
    Uri? uri, {
    Map<String, String>? headers = const {},
    dynamic body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            userContext,
            uri,
          ],
          {
            #headers: headers,
            #body: body,
          },
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #put,
            [
              userContext,
              uri,
            ],
            {
              #headers: headers,
              #body: body,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response>);
  @override
  _i4.Future<_i2.StreamedResponse> getStream(
    _i5.UserContext? userContext,
    _i6.StreamRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStream,
          [
            userContext,
            request,
          ],
        ),
        returnValue:
            _i4.Future<_i2.StreamedResponse>.value(_FakeStreamedResponse_1(
          this,
          Invocation.method(
            #getStream,
            [
              userContext,
              request,
            ],
          ),
        )),
      ) as _i4.Future<_i2.StreamedResponse>);
}
